name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  # Explore-GitHub-Actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
  #     - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  #     - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
  #     - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
  #     - run: echo "ðŸ This job's status is ${{ job.status }}."
  Output-Python-Licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Print The Environment
        run: |
          printenv
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.10
      # - name: Create `pip-licenses` environment
        # run: |
        #   python3 -m venv pip-licenses-env
        #   source pip-licenses-env/bin/activate
      - name: Install pip-licenses
        run: |
          pip install pip-licenses
      - name: Generate Licenses File
        run: |
          license_file=pip-licenses.md &&
            echo -e "# ${{ github.repository }} Licenses\n" &&
            pip-licenses \
            --from=mixed \
            --order=license \
            --format=markdown \
            >>$license_file &&
            echo -e "\n## Summary\n" &&
            pip-licenses \
            --from=mixed \
            --order=license \
            --format=markdown \
            --summary \
            >>$license_file &&
            cat $license_file



